---
# tasks file for db
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Include install_mongo
  ansible.builtin.include_tasks:
    file: install_mongo.yml

- name: Include iconfig_mongo
  ansible.builtin.include_tasks:
    file: config_mongo.yml
