---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
verifier:
  name: testinfra
