name: Run terraform validate

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  check_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
